#!/usr/bin/ruby
# vim: set encoding=utf-8 filetype=ruby :

require 'date'

def log(msg)
  puts "nupost: #{msg}"
end

wd = File.expand_path('~/github/felixhummel.github.com/_posts')
suffix = '.md'

filename = Date.today.to_s << '-' << ARGV.map {|s| s.split(/\s/)}.flatten.join('-').downcase.gsub(/[,]/,'_') << suffix
path = File.join(wd, filename)

stub = <<-EOS
---
layout: post
Title: #{ARGV.join(' ')}
---

# {{ page.title }}

EOS

file_is_new=false
if not File.exists? path
  File.open(path, 'w') {|f| f.write(stub)}
  created_time = File.mtime(path)
  file_is_new=true
  log "created #{path}"
end

# run vim
cmd = "vim \"#{path}\" +7"
system cmd

after_edit = File.mtime(path)
if file_is_new and created_time == after_edit
  File.delete(path)
  log "removed #{path}"
end
